S1 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      table_z - table_thickness];
S2 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      table_z - table_thickness];
S3 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      table_z - table_thickness];
S4 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      table_z - table_thickness];
S5 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      floor_level];
S6 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      floor_level];
S7 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      floor_level];
S8 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      floor_level];
SA = [S1,S2,S3,S4,S5,S6,S7,S8]';

S1 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      table_z - table_thickness];
S2 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      table_z - table_thickness];
S3 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      table_z - table_thickness];
S4 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      table_z - table_thickness];
S5 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      floor_level];
S6 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y + stand_y + stand_radius; 
      floor_level];
S7 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      floor_level];
S8 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y + stand_y - stand_radius; 
      floor_level];
SB = [S1,S2,S3,S4,S5,S6,S7,S8]';

S1 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      table_z - table_thickness];
S2 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      table_z - table_thickness];
S3 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      table_z - table_thickness];
S4 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      table_z - table_thickness];
S5 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      floor_level];
S6 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      floor_level];
S7 = [table_center - stand_x + stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      floor_level];
S8 = [table_center - stand_x - stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      floor_level];
SC = [S1,S2,S3,S4,S5,S6,S7,S8]';

S1 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      table_z - table_thickness];
S2 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      table_z - table_thickness];
S3 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      table_z - table_thickness];
S4 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      table_z - table_thickness];
S5 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      floor_level];
S6 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y - stand_y + stand_radius; 
      floor_level];
S7 = [table_center + stand_x + stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      floor_level];
S8 = [table_center + stand_x - stand_radius;
      dist_to_table - table_y - stand_y - stand_radius; 
      floor_level];
SD = [S1,S2,S3,S4,S5,S6,S7,S8]';